name: Java CI with Gradle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Make gradlew Executable
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Generate Reports
        run: ./gradlew generateCucumberReports

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: build/reports/**/*

      - name: Run Static Analysis
        run: ./gradlew sonar

      - name: Check Quality Gates
        run: ./gradlew sonarqube

      - name: Build Project
        run: ./gradlew build

      - name: Generate Documentation
        run: ./gradlew javadoc

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            build/libs/*.jar
            build/docs/javadoc/**/*

      - name: Deploy to Maven Repository
        run: ./gradlew publish
        env:
          MYMAVENREPO_USERNAME: ${{ secrets.MYMAVENREPO_USERNAME }}
          MYMAVENREPO_PASSWORD: ${{ secrets.REPO_PASS }}

      - name: Send Notifications
        run: |
          ./gradlew notifySlack
          ./gradlew sendMail