name: Java CI with Gradle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

  test:
    runs-on: windows-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Verify Java Version
        run: java -version
      - name: Run Tests
        run: |
          ./gradlew test --no-daemon --refresh-dependencies --stacktrace

  reports:
    runs-on: windows-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Generate Cucumber Reports
        run: ./gradlew generateCucumberReports --no-daemon --refresh-dependencies

  sonarqube-analysis:
    runs-on: windows-latest
    needs: reports
    steps:
      - uses: actions/checkout@v3
      - name: SonarQube Analysis
        run: |
          ./gradlew sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }} --no-daemon --refresh-dependencies

  build-and-document:
    runs-on: windows-latest
    needs: sonarqube-analysis
    steps:
      - uses: actions/checkout@v3
      - name: Build & Document
        run: |
          ./gradlew build --no-daemon --refresh-dependencies
          ./gradlew javadoc --no-daemon --refresh-dependencies

  deploy:
    runs-on: windows-latest
    needs: build-and-document
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: ./gradlew publish --no-daemon --refresh-dependencies