name: Java CI with Gradle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

  test:
    runs-on: windows-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: |
          ./gradlew test

  reports:
    runs-on: windows-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Generate Reports
        run: ./gradlew generateCucumberReports

  sonarqube-analysis:
    runs-on: windows-latest
    needs: reports
    steps:
      - uses: actions/checkout@v3
      - name: SonarQube Analysis
        run: |
          ./gradlew sonar

  build-and-document:
    runs-on: windows-latest
    needs: sonarqube-analysis
    steps:
      - uses: actions/checkout@v3
      - name: Build & Document
        run: |
          ./gradlew build
          ./gradlew javadoc

  deploy:
    runs-on: windows-latest
    needs: build-and-document
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: ./gradlew publish