name: Java CI with Gradle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run Tests
        run: ./gradlew test
      - name: Generate Reports
        run: ./gradlew generateCucumberReports
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: build/reports/**/*

  Code-Analysis:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run Static Analysis
        run: ./gradlew sonar

  Code-Quality:
    needs: Code-Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Check Quality Gates
        run: ./gradlew sonarqube

  Build:
    needs: Code-Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build Project
        run: ./gradlew build
      - name: Generate Documentation
        run: ./gradlew javadoc
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            build/libs/*.jar
            build/docs/javadoc/**/*

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Make gradlew Executable
        run: chmod +x gradlew

      - name: Déploiement du fichier jar sur myMavenRepo
        run: ./gradlew publish
        env:
          MYMAVENREPO_USERNAME: ${{ secrets.MYMAVENREPO_USERNAME }}
          MYMAVENREPO_PASSWORD: ${{ secrets.REPO_PASS }}

  Notification:
    needs: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Send Notifications
        run: |
          ./gradlew notifySlack
          ./gradlew sendMail